### ISSUE TITLE
Inconsistent Filesystem metrics

### ISSUE THREAD

**Issue by travisce** [virgo-agent-toolkit/rackspace-monitoring-agent#964] opened 2017-12-08 02:41 UTC
Howdy Agent Devs,

I'm seeing inconsistent metrics on the filesystem monitoring check for Cloud Databases. In the JPG attached, you can see that "Available 0.00B" and "Used 94.95%". Shouldn't "Used" be 100% here?

This was brought to my attention because the check's alarm did not fire a CRITICAL above 95% (it only reached 94.95%). The alarm condition is: "(percentage(metric['used'], metric['total']) > 95)"

/etc/debian_version => 7.6
df --version => df (GNU coreutils) 8.13
dpkg -l rackspace-monitoring-agent => 2.6.10

Thanks!
![maas-graphs-20171207](https://user-images.githubusercontent.com/5123941/33748588-fe897ee6-db8e-11e7-958f-a8e6b971e4db.jpg)

**Comment by itzg** [comment] 2018-01-04 22:09
We'll investigate further but looking at docs it might actually be "working as designed" since the [Rackspace Agent docs](https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#agent-filesystem) declare `used` as

> Used space on the filesystem, in kilobytes. This number does not include the reserved space. This is calculated as total - free

That corresponds to the `statvfs` [definition](http://manpages.ubuntu.com/manpages/precise/en/man3/statvfs.3.html) of `f_bavail`: 
>  free blocks for unprivileged users

As a solution/workaround, you can flip the numerical condition and use `available` such as

```
if (percentage(metric['available'], metric['total']) < 5) {
  return new AlarmStatus(CRITICAL, '...');
}
```

**Comment by jjbuchan** [comment] 2018-08-01 21:00
Closing this out due to "working as designed".  The alternative solution proposed by @itzg will work.

**Closed by jjbuchan** 2018-08-01 21:00 UTC
